POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thanhlam",
    "password": "123456789"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "hale1",
    "password": "hoho"
}

###
POST http://localhost:5000/api/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxM2FlNThmMWQ2MzRiZGFjMGY4NTNjYiIsInVzZXJuYW1lIjoiaGFsZTEiLCJwYXNzd29yZCI6IiRhcmdvbjJpJHY9MTkkbT00MDk2LHQ9MyxwPTEkc1Q3ZkFNdC9tazNQRlpCb003SEVjUSQ2TDhaVExYejdMQWx0d21iR1VDa2FrRENrZVB2c0VWZUxnVVZDVXpXN29JIiwiY3JlYXRlZEF0IjoiMjAyMS0wOS0xMFQwNDo1NjoyNy45NTlaIiwiX192IjowfSwiaWF0IjoxNjMzNjgyMzM3fQ.CavkGMUw5t5R7iXRk30VwRm-CAUbV6PrVCecn8XVH8g"
}


###
GET http://localhost:5000/api/task/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYxM2FlNThmMWQ2MzRiZGFjMGY4NTNjYiIsInVzZXJuYW1lIjoiaGFsZTEiLCJwYXNzd29yZCI6IiRhcmdvbjJpJHY9MTkkbT00MDk2LHQ9MyxwPTEkc1Q3ZkFNdC9tazNQRlpCb003SEVjUSQ2TDhaVExYejdMQWx0d21iR1VDa2FrRENrZVB2c0VWZUxnVVZDVXpXN29JIiwiY3JlYXRlZEF0IjoiMjAyMS0wOS0xMFQwNDo1NjoyNy45NTlaIiwiX192IjowfSwiaWF0IjoxNjMzNjgyNjAyLCJleHAiOjE2MzM2ODI2MzJ9.dd5KIU3LX3N6D5jKiMyCswSag3_PfsoovFCmUPjzaco


###
POST http://localhost:5000/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiMTg4ZjdiZmI3NDk2NzJjMDM2YTgiLCJpYXQiOjE2MzEyNjI4NjN9.TYpmaXaUyecIIicnHHEaCg7fWUmKsIuKVZcDnQpw_ag

{
    "title": "vue",
    "description": " learn everything vue",
    "status": ""
}
###
PUT http://localhost:5000/api/task/613b20d6ff3c50b0c6f56e53
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiMTg4ZjdiZmI3NDk2NzJjMDM2YTgiLCJpYXQiOjE2MzEyNjI4NjN9.TYpmaXaUyecIIicnHHEaCg7fWUmKsIuKVZcDnQpw_ag

{
     "title": "vue js 1",
    "description": "",
    "status": "WORKING"
}

###
DELETE  http://localhost:5000/api/task/613b20d6ff3c50b0c6f56e53
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiMTg4ZjdiZmI3NDk2NzJjMDM2YTgiLCJpYXQiOjE2MzEyNjI4NjN9.TYpmaXaUyecIIicnHHEaCg7fWUmKsIuKVZcDnQpw_ag
