POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "thanhlam",
    "password": "123456789"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "hale1",
    "password": "hoho"
}

###
POST http://localhost:5000/api/task
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiMTg4ZjdiZmI3NDk2NzJjMDM2YTgiLCJpYXQiOjE2MzEyNjI4NjN9.TYpmaXaUyecIIicnHHEaCg7fWUmKsIuKVZcDnQpw_ag

{
    "title": "vue",
    "description": " learn everything vue",
    "status": ""
}
###
PUT http://localhost:5000/api/task/613b20d6ff3c50b0c6f56e53
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MTNiMTg4ZjdiZmI3NDk2NzJjMDM2YTgiLCJpYXQiOjE2MzEyNjI4NjN9.TYpmaXaUyecIIicnHHEaCg7fWUmKsIuKVZcDnQpw_ag

{
     "title": "vue js 1",
    "description": "",
    "status": "WORKING"
}